// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirjr7Mv6Hj8CuKjijnchpKy1YIeJ47dc',
    appId: '1:611063996525:web:39d50056048e131d475f64',
    messagingSenderId: '611063996525',
    projectId: 'kayoola-drivers-app',
    authDomain: 'kayoola-drivers-app.firebaseapp.com',
    storageBucket: 'kayoola-drivers-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3TRVj8XaSEuDQ1ZwKaM47LFzFZJ2qrTQ',
    appId: '1:611063996525:android:9650986535ee7837475f64',
    messagingSenderId: '611063996525',
    projectId: 'kayoola-drivers-app',
    storageBucket: 'kayoola-drivers-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLc6-3v-s6HfQwY4oc58p-xRx5Lmhtpg',
    appId: '1:611063996525:ios:548b77228b8b1a19475f64',
    messagingSenderId: '611063996525',
    projectId: 'kayoola-drivers-app',
    storageBucket: 'kayoola-drivers-app.appspot.com',
    iosClientId: '611063996525-0i34kq5keb74fmi7inl6korvq9mhjenh.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayoolaDriversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLc6-3v-s6HfQwY4oc58p-xRx5Lmhtpg',
    appId: '1:611063996525:ios:734ed2e4b68704c7475f64',
    messagingSenderId: '611063996525',
    projectId: 'kayoola-drivers-app',
    storageBucket: 'kayoola-drivers-app.appspot.com',
    iosClientId: '611063996525-5agj0o828pg9rg86qmu098iu7ror5e29.apps.googleusercontent.com',
    iosBundleId: 'com.example.kayoolaDriversApp.RunnerTests',
  );
}
